version: 2
general:
  branches:
    only:
     - master
     - /feature-.*/
jobs:
  build:
    environment:
      - NODE_ENV: development
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    environment:
      - NODE_ENV: development
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Test
          command: |
            export PATH=/home/circleci/project/node_modules/.bin:$PATH
            echo $PATH
            ls -R $HOME
            npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - run:
          name: Coverage
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master