version: 2
general:
  branches:
    only:
     - master
     - /feature-.*/
jobs:
  test:
    environment:
      - NODE_ENV: development
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - run:
          name: Coverage
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only: master